[workspace]
members = ["xp-sqlx", "proc_macro"]
resolver = "2"

[workspace.dependencies]
polars = { version = "0.40", features = [
    "lazy",
    "serde",
    "parquet",
    "polars-io",
    "temporal",
] }
