[package]
name = "xp-sqlx"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
derive_more = "0.99"
eframe = "0.27"
egui = "0.27"
egui_extras = "0.27"
egui_inbox = "0.4"
futures = "0.3"
polars = { version = "0.40", features = [
    "lazy",
    "serde",
    "parquet",
    "polars-io",
    "temporal",
] }
sqlx = { version = "0.7", features = [
    "mysql",
    "runtime-tokio",
    "tls-rustls",
    "macros",
    "chrono",
] }
tokio = { version = "1.37", features = ["full", "tracing"] }

[dev-dependencies]
criterion = { version = "0.5.1", features = [
    "async_tokio",
    "futures",
    "html_reports",
    "csv",
] }

[[bench]]
name = "transpose_bench"
harness = false
