[package]
name = "xp-sqlx"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.7.4", features = ["mysql", "runtime-tokio"] }
tokio = { version = "1.37.0", features = ["full", "tracing"] }
