[package]
name = "xp-sqlx"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
derive_more = "0.99.17"
futures = "0.3.30"
sqlx = { version = "0.7.4", features = ["mysql", "runtime-tokio", "tls-rustls", "macros", "chrono"] }
tokio = { version = "1.37.0", features = ["full", "tracing"] }
